ionic plugin remove com.ionic.keyboard
ionic plugin add com.ionic.keyboard
ionic plugin remove com.phonegap.plugins.barcodescanner
ionic plugin add com.phonegap.plugins.barcodescanner
ionic plugin remove com.phonegap.plugins.fileopener  
ionic plugin add com.phonegap.plugins.fileopener
ionic plugin remove cordova-plugin-network-information
ionic plugin add cordova-plugin-network-information
ionic plugin remove de.appplant.cordova.plugin.email-composer
ionic plugin add de.appplant.cordova.plugin.email-composer
ionic plugin remove nl.x-services.plugins.flashlight
ionic plugin add nl.x-services.plugins.flashlight
ionic plugin remove org.apache.cordova.camera
ionic plugin add org.apache.cordova.camera
ionic plugin remove org.apache.cordova.console
ionic plugin add org.apache.cordova.console
ionic plugin remove org.apache.cordova.device
ionic plugin add org.apache.cordova.device
ionic plugin remove org.apache.cordova.file
ionic plugin add org.apache.cordova.file
ionic plugin remove org.apache.cordova.file-transfer
ionic plugin add org.apache.cordova.file-transfer
ionic plugin remove org.apache.cordova.globalization
ionic plugin add org.apache.cordova.globalization
ionic plugin remove org.apache.cordova.inappbrowser
ionic plugin add org.apache.cordova.inappbrowser
ionic plugin remove org.cloudsky.cordovaplugins.zbar
ionic plugin add org.cloudsky.cordovaplugins.zbar
ionic plugin remove plugin.http.request
ionic plugin add plugin.http.request

